[package]
name = "persistence"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
idb = "0.6"
wasm-bindgen = "0.2"
async-trait = "0.1"
serde-wasm-bindgen = "0.6.5"
thiserror = "1"
